# Generated by Django 4.0.4 on 2022-05-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.EmailField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=128, null=True)),
                ('birthday', models.DateTimeField(null=True)),
                ('department', models.CharField(max_length=128, null=True)),
                ('cellphone', models.CharField(max_length=64, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
