# Generated by Django 4.0.4 on 2022-05-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
